name := "IPTool"
version := "1.0"
scalaVersion := "3.3.1"
libraryDependencies += "io.circe" %% "circe-core" % "0.14.1"
libraryDependencies += "io.circe" %% "circe-generic" % "0.14.1"
libraryDependencies += "io.circe" %% "circe-parser" % "0.14.1"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.2.10" % "test"